name: "DHondhu Maharaaj"
on:
  push:
    branches:
      - 'features/**'
      - 'main'
      - 'hotfix/**'
jobs:
  terraformInit:
    name: Terraform Ititwa
    runs-on: ubuntu-latest
    steps: 
    - name: Dhondhu Maharaj
      run: echo Dhondhu Maharaaj
      
    
